/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default  class CommonConstants {
  /**
   * AI-指令内容区
   */
  static readonly COMMAND_DEFAULT_FONT_COLOR: string = '#31373d';
  static readonly COMMAND_SECOND_FONT_COLOR: string = '#00aecc';
  static readonly COMMAND_TITLE_FONT_SIZE: number = 32;
  static readonly COMMAND_DEFAULT_FONT_SIZE: number = 14;
  static readonly COMMAND_TITLE_FONT_WEIGHT: number = 600;
  static readonly COMMAND_ICON_DEFAULT_WEIGHT: number = 16;
  static readonly COMMAND_ICON_DEFAULT_HEIGHT: number = 16;

  /**
   * Button width.
   */
  static readonly BUTTON_WIDTH: string = '42%';

  /**
   * Button spacing.
   */
  static readonly BUTTON_SPACING: number = 12;

  /**
   * Row spacing.
   */
  static readonly ROW_SPACING: number = 16;
}