export class ThemeConfig {
  static PaletteTheme: string = '#00aecc' //色彩主题
  static readonly TextBodyColor: string = '#31373d' //正文颜色
  static readonly SecondaryTextColor: string = '#A4AAB2' //二级文字颜色
  static readonly TextWeight_400: number = 400
  static readonly TextWeight_500: number = 500
  static readonly TextWeight_600: number = 600
  static readonly TextSize_12: number = 12
  static readonly TextSize_14: number = 14
  static readonly TextSize_18: number = 18
  static readonly TextSize_24: number = 24
}