export class CommonConfig {
  static readonly PaletteTheme: string = '#00AECC' //主题色
  static readonly commonBackgroundColor: string = '#F8F8F8' //通用背景色
  static readonly hintTextColor: string = '#999' //提示文字颜色
  static readonly hintTextColor_select: string = '#333333' //提示文字颜色
  static readonly secondaryTextColor: string = '#A4AAB2' //二级文字颜色
  static readonly fontSize_11: number = 11 //提示文字
  static readonly fontSize_12: number = 12 //小正文
  static readonly fontSize_14: number = 14 //正文
  static readonly fontSize_16: number = 16 //小标题
  static readonly fontSize_18: number = 18 //大标题
  static readonly fontSize_24: number = 24
  static readonly fontWeight_400: number = 400
  static readonly fontWeight_700: number = 700
}