export { ConnectDevice,Communication,DeviceInfo,MouseICType,KeyPressType,DeviceArrayType,DPI_currInfoModel,PRODUCT_TYPE } from './src/main/ets/components/Communication';
export { SmartMouseAudioProcessor } from './src/main/ets/utils/SmartMouseAudioProcessor';
export { AudioFileManager } from './src/main/ets/utils/AudioFileManager';
export { AudioWebSocketHandler,inputMessageModel } from './src/main/ets/utils/AudioWebSocketHandler';
export { translate_Params,translate_Response ,getModelInfo_Params} from './src/main/ets/model/MouseInfoModel';
export { _translate ,_getModelInfo} from './src/main/ets/viewmodel/UserViewModel';
export { keyConfigExclusion} from './src/main/ets/utils/keyConfigExclusion';
