// export { MainPage } from './src/main/ets/components/MainPage';
export { http, BaseParams } from './src/main/ets/http/HttpRequest'

export { AudioWebSocketHandler, inputMessageModel } from './src/main/ets/webSocket/AudioWebSocketHandler'

export { OpenFileWithSystemApp } from './src/main/ets/api/OpenFileWithSystemApp' //打开文件

export { Call_PHONE } from './src/main/ets/api/Call_PHONE' //打开通话应用

export { AudioRecorderManager } from './src/main/ets/api/AudioRecorderManager' //本地麦克风管理

export { adapterManager, AdapterManager } from './src/main/ets/api/AdapterManager' //蓝牙状态管理

export { DraggableResizableRect } from './src/main/ets/api/DraggableResizableRect' //绘制矩形——截图翻译

export { OnlineAudioPlayer, AudioPlayerConfig, AudioPlayerEvents, PlaybackState
} from './src/main/ets/api/AudioRenderer' //PCM音频播放
